"""add source health tracking

Revision ID: 348ddb3629ad
Revises: 24172d6a8ac4
Create Date: 2026-09-30 13:42:05.349670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348ddb3629ad'
down_revision: Union[str, Sequence[str], None] = '24172d6a8ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "sources",
        sa.Column(
            "last_checked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.add_column(
        "sources",
        sa.Column(
            "last_success_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.add_column(
        "sources",
        sa.Column(
            "last_error",
            sa.Text(),
            nullable=True,
        ),
    )

    # Add temporarily as nullable because existing sources already exist.
    op.add_column(
        "sources",
        sa.Column(
            "consecutive_failures",
            sa.Integer(),
            nullable=True,
        ),
    )

    # Existing sources start with zero consecutive failures.
    op.execute(
        """
        UPDATE sources
        SET consecutive_failures = 0
        WHERE consecutive_failures IS NULL
        """
    )

    # Now that existing rows have a value, enforce NOT NULL.
    op.alter_column(
        "sources",
        "consecutive_failures",
        existing_type=sa.Integer(),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'consecutive_failures')
    op.drop_column('sources', 'last_error')
    op.drop_column('sources', 'last_success_at')
    op.drop_column('sources', 'last_checked_at')
    # ### end Alembic commands ###
